package com.myspace.dynamic_subprocess_kjar;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcessExchangeModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String subprocess;
	private java.lang.String message;

	public ProcessExchangeModel() {
	}

	public java.lang.String getSubprocess() {
		return this.subprocess;
	}

	public void setSubprocess(java.lang.String subprocess) {
		this.subprocess = subprocess;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public ProcessExchangeModel(java.lang.String subprocess,
			java.lang.String message) {
		this.subprocess = subprocess;
		this.message = message;
	}
	
	public String toString() {
	    return "Subprocess: " + subprocess + "; Message: " + message;
	}

}