package com.myspace.dynamic_subprocess_kjar;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcessExchangeModel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ProcessExchangeModel() {
    }




}