package com.myspace.dynamic_subprocess_kjar;

import org.kie.api.runtime.process.WorkflowProcessInstance;

rule "Product X process"
no-loop true
when
    $product: Product (name == "Product X")
    $process : WorkflowProcessInstance( )
then
    WorkflowProcessInstance $processInstance = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance($process.getId());
    $processInstance.setVariable( "processExchange", new ProcessExchangeModel("child-a", "Product with price: " + $product.getPrice()) );
    retract($process);
end