package com.myspace.dynamic_subprocess_kjar;

rule "Product X process"
no-loop true
when
    $p: Product (name == "Product X"),
    $process : WorkflowProcessInstance( )
then
    WorkflowProcessInstance $p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance($process.getId()); //casting to WorkflowProcessInstance is essential
    $p.setVariable( "processExchange", new ProcessExchange("child-a", "Product with price: " + $p.getPrice() );
    retract($process);
end